/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:00f885bb-e979-4ade-841d-b758b229a888",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_BsXaulFX3",
    "aws_user_pools_web_client_id": "6m78abj6h813kc4n4lg4k1frvh",
    "oauth": {}
};


export default awsmobile;
